### ISSUE TITLE
Highlighted content is positioned wrong

### ISSUE THREAD

**Issue by vikeen** [frichti/react-native-tips#20]
I've tried a number of tooltip frameworks and I'm coming up short with all of them. Assuming the problem is with my code, but not sure where to start debugging. Below are screenshots of what is happening.

## Component

```js
<ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
    {
        paths.order.map((pathUid) => {
            const path = paths.byId[pathUid];
            return (
                <Tips
                    visible={this.state.v}
                    text="When you are logged, you can click here to acceed to the menu and edit your profile."
                    position={"none"}
                    enableChildrenInteraction={true}
                >
                    <PathItem
                        key={path.uid}
                        onPress={this.goToPath}
                        path={path}
                        pathProgress={pathProgress}/>
                </Tips>
            );
        })
    }
</ScrollView>
```

<img width="371" alt="screen shot 2018-06-08 at 3 51 35 pm" src="https://user-images.githubusercontent.com/1700158/41180530-2065a7bc-6b34-11e8-862e-6079101ae17e.png">
<img width="369" alt="screen shot 2018-06-08 at 3 51 43 pm" src="https://user-images.githubusercontent.com/1700158/41180531-20825cfe-6b34-11e8-98ea-204b74e54858.png">

**Comment by myvertigo** [comment]
Hello !

Sometimes the `measure` event to detect the position of the element is bad. It is generally caused by animated or dynamic element.

You have two choice to correct this offset :
 - Use `offsetLeft` and `offsetTop` props
 - Use `tooltipContainerStyle` to edit the StyleSheet properties of the container.

I think that `offsetLeft` and `offsetTop` is the right solution.

Hope that will solve your problem.
